services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=kapirun
      - POSTGRES_PASSWORD=kapirun
      - POSTGRES_DB=kapirun
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kapirun"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - kapi_postgres_data:/var/lib/postgresql/data

volumes:
  kapi_postgres_data:

