services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=kapirun
      - POSTGRES_PASSWORD=kapirun
      - POSTGRES_DB=kapirun
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kapirun"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kapi-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://kapirun:kapirun@db:5432/kapirun
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kapi-network

volumes:
  postgres_data:

networks:
  kapi-network:
    driver: bridge
